CREATE DATABASE `imagesdb`;
USE `imagesdb`;
DROP TABLE IF EXISTS `images`;
CREATE TABLE `images` (
`img_id` TINYINT NOT NULL AUTO_INCREMENT,
`img_url_code` VARCHAR(10) NOT NULL,
`img_url_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`img_image_name` VARCHAR(255) NOT NULL,
`img_dir_name` VARCHAR(8) NOT NULL,
PRIMARY KEY (`img_id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;